# Generated by Django 3.0.2 on 2020-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
